### ISSUE TITLE
使用多个参数的任意命令时有很大概率报错

### ISSUE THREAD

**Issue by TRDSCSH** [daisukiKaffuChino/KoharuBan-Java#1]
使用 `/test arg0 arg1` 命令时
```
[15:37:06 INFO]: 0x0FFFFFFFFFFFFF issued server command: /test arg0 arg1
[15:37:06 ERROR]: Could not pass event PlayerCommandPreprocessEvent to KoharuBanJava v0.1.0-dev
java.lang.StringIndexOutOfBoundsException: Range [10, 4) out of bounds for length 4
        at jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) ~[?:?]
        at jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) ~[?:?]
        at jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) ~[?:?]
        at jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112) ~[?:?]
        at jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349) ~[?:?]
        at java.lang.String.checkBoundsBeginEnd(String.java:4914) ~[?:?]
        at java.lang.String.substring(String.java:2876) ~[?:?]
        at java.lang.String.substring(String.java:2849) ~[?:?]
        at github.daisukiKaffuChino.koharu.listener.PlayerActionListener.onPlayerCommandPreprocess(PlayerActionListener.java:122) ~[KoharuBanJava-0.1.0-dev.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1008.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-497]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2206) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2190) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1343) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

使用 `give` 命令时
```
[15:34:56 INFO]: 0x0FFFFFFFFFFFFF issued server command: /give 0x0FFFFFFFFFFFFF 11disc
[15:34:56 WARN]: [KoharuBanJava] FFFFFF
[15:34:56 WARN]: [KoharuBanJava] No enum constant org.bukkit.Material.FFFFFF
```

- - -
问题出在这段 `能跑就行` 的代码 (来自 `PlayerActionListener.java`)
```
String substring = split[2].toUpperCase().substring(10);
```

**Comment by daisukiKaffuChino** [comment]
这下终于彻底严查力
